### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [ericberglund117/mod_0_skills#1]
@ericberglund117 overall, nice work on this! In general, good clear naming conventions. It's clear to me how you intend to affect an attribute based on a method name. It's super close, but there are a few updates I'd like for you to make before we consider you `technical ready`:
* [ ] Make sure that your boolean data types are syntactically correct
* [ ] What would the updated arrays look like in your instance files after your methods that affect the arrays are ran? Please show the fully updated array instead the new or removed element.

**Comment by ericberglund117** [comment]
@damwhit I updated the boolean data types (took away the quotation marks) and included the fully updated array after making the chipotle burrito vegan and adding guacamole.

I hope this is what you were talking about. 

Thank you!

**Comment by damwhit** [comment]
@ericberglund117 these updates look good! You are officially `technical ready`! Keep up the hard work moving forward!
